---
name: ♻️ Sync Labels
on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
  workflow_dispatch:
jobs:
  labels:
    name: ♻️ Sync labels
    permissions:
      contents: read
      issues: write
      metadata: read
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: ♻️ Run Label Sync
        uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
